version: '3.3'

volumes:
  postgres_data:
  static:
  media:

services:

  postgres:
    container_name: foodgram-database
    image: postgres:16
    environment:
      - POSTGRES_USER=foodgram_admin
      - POSTGRES_PASSWORD=kekeispassword
      - POSTGRES_DB=foodgram
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    build: ../backend
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    volumes:
      - static:/static/
      - media:/media/

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    depends_on:
      - frontend
      - backend
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/etc/nginx/html/api/static
      - media:/etc/html/media