# Generated by Django 5.1.7 on 2025-04-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_remove_subscription_u_subscriptions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='subscribing_user',
        ),
    ]
