# Generated by Django 5.1.7 on 2025-03-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredientandrecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingridients'
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingridients',
            field=models.ManyToManyField(through='recipes.IngredientAndRecipe', to='recipes.ingredient', verbose_name='Ингридиенты'),
        ),
    ]
