# Generated by Django 5.1.7 on 2025-04-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_measure_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='u_ingredient',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='u_ingredient'),
        ),
    ]
