# Generated by Django 5.1.7 on 2025-04-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteuserrecipes',
            old_name='user',
            new_name='subscribing_user',
        ),
        migrations.RenameField(
            model_name='usercart',
            old_name='user',
            new_name='subscribing_user',
        ),
    ]
