# Generated by Django 5.1.7 on 2025-04-04 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_rename_user_favoriteuserrecipes_subscribing_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriteuserrecipes',
            name='u_favorite_user_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='usercart',
            name='u_user_cart',
        ),
        migrations.AddConstraint(
            model_name='favoriteuserrecipes',
            constraint=models.UniqueConstraint(fields=('subscribing_user', 'recipe'), name='u_favorite_user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='usercart',
            constraint=models.UniqueConstraint(fields=('subscribing_user', 'recipe'), name='u_user_cart'),
        ),
    ]
