# Generated by Django 5.1.7 on 2025-04-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_ingredientandrecipe_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteuserrecipes',
            old_name='subscribing_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usercart',
            old_name='subscribing_user',
            new_name='user',
        ),
    ]
