# Generated by Django 5.1.7 on 2025-04-08 12:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_remove_favoriteuserrecipes_u_favorite_user_recipe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCart',
            new_name='Cart',
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продуктыы'},
        ),
        migrations.AlterModelOptions(
            name='ingredientandrecipe',
            options={'verbose_name': 'Продукт и рецепт', 'verbose_name_plural': 'Продукты и рецепты'},
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='u_user_cart',
        ),
        migrations.RemoveConstraint(
            model_name='favoriteuserrecipes',
            name='u_favorite_user_recipe',
        ),
        migrations.RemoveField(
            model_name='ingredientandrecipe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.IngredientAndRecipe', to='recipes.ingredient', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=64, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ingredientandrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='ingredientandrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления в минутах'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteuserrecipes',
            unique_together={('user', 'recipe')},
        ),
    ]
