# Generated by Django 5.1.7 on 2025-04-08 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_rename_usercart_cart_alter_ingredient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteuserrecipes',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='u_cart'),
        ),
        migrations.AddConstraint(
            model_name='favoriteuserrecipes',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='u_favoriteuserrecipes'),
        ),
    ]
